server:
  env: test
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  redis:
    network: tcp
    addr: redis-svc-6p5kp:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    username: ""
    password: "test"
  database:
    xs:
      max_idle_conns: 1
      max_open_conns: 100
      conn_max_lifetime: 30s
      conn_max_idle_time: 30s
      master: normal:HelloGogo123456@tcp(rds-mysql-test.rwlb.rds.aliyuncs.com:3306)/xs
      slaves:
        - normal:HelloGogo123456@tcp(rds-mysql-test.rwlb.rds.aliyuncs.com:3306)/xs
log:
  level: DEBUG
otel:
  service_name: ""
  sample_rate: 1.0
  endpoint: "" # tracing-analysis-dc-sg-internal.aliyuncs.com
  path: "" # adapt_1iu42593ahf@xxxxxxxx1/api/otlp/traces
